version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - "./nginx:/www/data/"
  web:
    build: ./web
    ports:
      - "8000:8000"
    environment: 
      - CFP_MONGO_HOST=mongo
    depends_on:
      - mongo
    volumes:
      - "./web:/usr/src/app"
    entrypoint:
      - gunicorn
      - api:app
      - -b
      - 0.0.0.0:8000
      - --reload
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
