version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
