apiVersion: batch/v1
kind: Job
metadata:
  name: scraper
  labels:
    chapter: jobs
spec:
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
        - name: scraper
          image: gcr.io/iosdc-2018-cfp-staging/scraper:0.1.0
          imagePullPolicy: Always
      restartPolicy: OnFailure
