apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-phase1
  labels:
    chapter: jobs
spec:
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
        - name: scraper
          image: gcr.io/iosdc-2018-cfp/scraper:0.2.0
          imagePullPolicy: Always
      restartPolicy: OnFailure
