apiVersion: batch/v1
kind: Job
metadata:
  name: patch-v3
  labels:
    chapter: jobs
spec:
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
        - name: scraper
          image: gcr.io/iosdc-2018-cfp-miya/scraper-patch:0.0.3
          imagePullPolicy: Always
      restartPolicy: OnFailure
