apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: penginmura-tech-certificate
  namespace: default
spec:
  secretName: cert-manager-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: '*.penginmura.tech'
  dnsNames:
  - penginmura.tech
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - '*.penginmura.tech'
      - penginmura.tech
