apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        kubernetes.io/change-cause: "change replicas 1 to 3"
    spec:
      containers:
      - name: web
        image: gcr.io/iosdc-2018-cfp/web:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
